package uk.gov.netz.api.workflow.request.core.domain.constants;

import lombok.experimental.UtilityClass;

@UtilityClass
public class RequestActionPayloadTypes {
	
	public String RFI_SUBMITTED_PAYLOAD = "RFI_SUBMITTED_PAYLOAD";
	
	public String RFI_RESPONSE_SUBMITTED_PAYLOAD = "RFI_RESPONSE_SUBMITTED_PAYLOAD";
    
	public String RDE_SUBMITTED_PAYLOAD = "RDE_SUBMITTED_PAYLOAD";
	public String RDE_REJECTED_PAYLOAD = "RDE_REJECTED_PAYLOAD";
	public String RDE_DECISION_FORCED_PAYLOAD = "RDE_DECISION_FORCED_PAYLOAD";

	public String PAYMENT_MARKED_AS_PAID_PAYLOAD = "PAYMENT_MARKED_AS_PAID_PAYLOAD";
	public String PAYMENT_MARKED_AS_RECEIVED_PAYLOAD = "PAYMENT_MARKED_AS_RECEIVED_PAYLOAD";
	public String PAYMENT_COMPLETED_PAYLOAD = "PAYMENT_COMPLETED_PAYLOAD";
	public String PAYMENT_CANCELLED_PAYLOAD = "PAYMENT_CANCELLED_PAYLOAD";
}
