package uk.gov.netz.api.documenttemplate.service;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.core.io.ByteArrayResource;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.util.LinkedMultiValueMap;
import org.springframework.util.MultiValueMap;
import org.springframework.web.client.RestTemplate;
import org.springframework.web.util.UriComponentsBuilder;
import uk.gov.netz.api.documenttemplate.config.DocumentGeneratorProperties;
import uk.gov.netz.api.documenttemplate.config.RestEndPointEnum;
import uk.gov.netz.api.documenttemplate.domain.dto.DocumentParameters;
import uk.gov.netz.api.restclient.RestClientApi;
import uk.gov.netz.docgenerator.client.DocumentGeneratorClient;
import uk.gov.netz.docgenerator.client.model.AsyncJobReceipt;
import uk.gov.netz.docgenerator.client.model.DocumentGenerationPriority;
import uk.gov.netz.docgenerator.client.model.DocumentGenerationRequest;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.util.Map;

@ExtendWith(MockitoExtension.class)
public class DocumentGeneratorRemoteClientServiceTest {

	@InjectMocks
    private DocumentGeneratorRemoteClientService documentGeneratorRemoteClientService;

    @Mock
    private DocumentGeneratorProperties properties;

    @Mock
    private RestTemplate restTemplate;
    
    @Mock
    private DocumentGeneratorClient documentGeneratorClient;
    
    @Test
    void generateDocument() {
    	byte[] source = "some bytes".getBytes();
    	String outputFilename = "targetFile.pdf";
    	String baseUrl = "http://localhost:8081";
    	
    	final HttpHeaders httpHeaders = new HttpHeaders();
    	httpHeaders.setContentType(MediaType.MULTIPART_FORM_DATA);
    	
    	final MultiValueMap<String, Object> body = new LinkedMultiValueMap<>();
		body.add("file", new ByteArrayResource(source) {
	        @Override
	        public String getFilename() {
	            return "source";
	        }
	    });
		body.add("parameters", DocumentParameters.builder().outputFilename(outputFilename).build());
    	
    	byte[] resultExpected = "some generated bytes".getBytes();

    	RestClientApi appRestApi = RestClientApi.builder()
				.uri(UriComponentsBuilder
						.fromUriString(baseUrl)
						.path(RestEndPointEnum.GENERATE.getPath())
						.build()
						.toUri())
				.restEndPoint(RestEndPointEnum.GENERATE)
				.headers(httpHeaders)
				.restTemplate(restTemplate)
				.body(body)
				.build();

        when(properties.getUrl()).thenReturn(baseUrl);
        when(restTemplate.exchange(appRestApi.getUri(), RestEndPointEnum.GENERATE.getMethod(),
                new HttpEntity<>(body, httpHeaders), new ParameterizedTypeReference<byte[]>() {}))
                .thenReturn(new ResponseEntity<>(resultExpected, HttpStatus.OK));

        byte[] resultActual = documentGeneratorRemoteClientService.generateDocument(source, outputFilename);
        
        assertThat(resultActual).isEqualTo(resultExpected);

        verify(properties, times(1)).getUrl();
        verify(restTemplate, times(1)).exchange(appRestApi.getUri(), RestEndPointEnum.GENERATE.getMethod(),
                new HttpEntity<>(body, httpHeaders), new ParameterizedTypeReference<byte[]>() {});
    }

    @Test
    void generateDocumentWithNormalize() {
    	byte[] source = "some bytes".getBytes();
    	String outputFilename = "targetFile.pdf";
    	String baseUrl = "http://localhost:8081";
    	
    	final HttpHeaders httpHeaders = new HttpHeaders();
    	httpHeaders.setContentType(MediaType.MULTIPART_FORM_DATA);
    	
    	final MultiValueMap<String, Object> body = new LinkedMultiValueMap<>();
		body.add("file", new ByteArrayResource(source) {
	        @Override
	        public String getFilename() {
	            return "source";
	        }
	    });
		body.add("parameters", DocumentParameters.builder().outputFilename(outputFilename).normalize(true).build());
    	
    	byte[] resultExpected = "some generated bytes".getBytes();

    	RestClientApi appRestApi = RestClientApi.builder()
				.uri(UriComponentsBuilder
						.fromUriString(baseUrl)
						.path(RestEndPointEnum.GENERATE.getPath())
						.build()
						.toUri())
				.restEndPoint(RestEndPointEnum.GENERATE)
				.headers(httpHeaders)
				.restTemplate(restTemplate)
				.body(body)
				.build();

        when(properties.getUrl()).thenReturn(baseUrl);
        when(restTemplate.exchange(appRestApi.getUri(), RestEndPointEnum.GENERATE.getMethod(),
                new HttpEntity<>(body, httpHeaders), new ParameterizedTypeReference<byte[]>() {}))
                .thenReturn(new ResponseEntity<>(resultExpected, HttpStatus.OK));

        byte[] resultActual = documentGeneratorRemoteClientService.generateDocument(source, outputFilename, true);
        
        assertThat(resultActual).isEqualTo(resultExpected);

        verify(properties, times(1)).getUrl();
        verify(restTemplate, times(1)).exchange(appRestApi.getUri(), RestEndPointEnum.GENERATE.getMethod(),
                new HttpEntity<>(body, httpHeaders), new ParameterizedTypeReference<byte[]>() {});
    }
    
    @Test
    void generateDocumentAsync() throws Exception {
    	byte[] source = "some bytes".getBytes();
    	Map<String, String> documentMetadata = Map.of(
    			"entr1key", "entr1val"
    			);
    	
    	AsyncJobReceipt receipt = AsyncJobReceipt.builder().jobId("job").build();
    	
        when(documentGeneratorClient.submitAsync(Mockito.any(DocumentGenerationRequest.class))).thenReturn(receipt);
    	
        var result = documentGeneratorRemoteClientService.generateDocumentAsync(source, documentMetadata, true);
    	assertThat(result).isEqualTo(receipt.getJobId());

        ArgumentCaptor<DocumentGenerationRequest> requestCaptor = ArgumentCaptor.forClass(DocumentGenerationRequest.class);
        verify(documentGeneratorClient, times(1)).submitAsync(requestCaptor.capture());

        DocumentGenerationRequest request = requestCaptor.getValue();
        assertThat(request.getDocxBytes()).isEqualTo(source);
        assertThat(request.getMetadata()).isEqualTo(documentMetadata);
        assertThat(request.isNormalize()).isTrue();
        assertThat(request.getPriority()).isEqualTo(DocumentGenerationPriority.HIGH);
    }

    @Test
    void generateDocumentAsyncWithPriority() throws Exception {
    	byte[] source = "some bytes".getBytes();
    	Map<String, String> documentMetadata = Map.of(
    			"entr1key", "entr1val"
    			);
    	
    	AsyncJobReceipt receipt = AsyncJobReceipt.builder().jobId("job").build();
    	
        when(documentGeneratorClient.submitAsync(Mockito.any(DocumentGenerationRequest.class))).thenReturn(receipt);
    	
        var result = documentGeneratorRemoteClientService.generateDocumentAsync(
                source,
                documentMetadata,
                false,
                DocumentGenerationPriority.LOW);
    	assertThat(result).isEqualTo(receipt.getJobId());

        ArgumentCaptor<DocumentGenerationRequest> requestCaptor = ArgumentCaptor.forClass(DocumentGenerationRequest.class);
        verify(documentGeneratorClient, times(1)).submitAsync(requestCaptor.capture());

        DocumentGenerationRequest request = requestCaptor.getValue();
        assertThat(request.getDocxBytes()).isEqualTo(source);
        assertThat(request.getMetadata()).isEqualTo(documentMetadata);
        assertThat(request.isNormalize()).isFalse();
        assertThat(request.getPriority()).isEqualTo(DocumentGenerationPriority.LOW);
    }
}
